version: '3'
services:
  api:
    build: .
    command: rails s -b 0.0.0.0 -p 4000
    ports:
      - 80:4000
    volumes:
      - .:/travels
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - travels-data:/var/lib/postgresql/data
volumes:
  travels-data:
